development:
  dialect: mysql
  datasource: ${DOCKER_DB_MYSQL_USER}:${DOCKER_DB_MYSQL_PASSWORD}@tcp(${DOCKER_DB_MYSQL_HOST}:${DOCKER_DB_MYSQL_PORT})/${DOCKER_DB_MYSQL_NAME}?parseTime=true
  dir: migrations/mysql