version: "3.8"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    entrypoint: ["./start.sh"]
  db:
    image: mysql:8
    restart: always
    ports:
      - '33062:3306'
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: records
